### ISSUE TITLE
How to reproduce your work with png format data

### ISSUE THREAD

**Issue by hubin111** [UttaranB127/take_an_emotion_walk#1]
Dear Uttaran：
 
Thank you for your contribution, but we want to realize the emotion recognition from the png format of the image to the end. However, during the reproduction process, it is found that there are only some key points of the human skeleton in the data set (E-Gait) you provided. Would you like to ask if you can tell how to process the data preprocessing from the picture to the E-Gait data set. If you can receive the data set (E-Gait) you shared in png format. We will be very grateful to you, and we are very eager to hear back.

Best wishes

**Comment by UttaranB127** [comment]
Hi,

Given an input image, you can use one of the available 2D/3D pose extraction methods as per your need to generate the skeletons. Following are the pose extraction methods we have looked into:

For 2D:
1. OpenPose: https://github.com/CMU-Perceptual-Computing-Lab/openpose
2. Lightweight Pose Detection: https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch (there is also a newer version of this work available)

For 3D:
1. Generative Pose: https://github.com/ssfootball04/generative_pose
2. Lightweight Pose Detection: https://github.com/Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch

However we won't be able to share the original subject images from our dataset because of IRB restrictions. Hope you understand, and hope this helps.

Please reach out if you have more questions!

**Comment by hubin111** [comment]
Dear Uttaran：

Thank you for your patient reply. We have now obtained the 3D coordinates of the joint points through the method you provided, but there are only 16 3D coordinates of the joint points. Can you tell me how to deal with the data file from 3D coordinates to manufacturing the format you provided.

In addition, in the process of reproducing the results of the article, we found that the ewalk data set, pre-trained feature file and its weight file were not provided. In order to better reproduce your work, can you provide the above files of the ewalk data set. We will thank you very much and are very eager to hear from you.

Best wishes

**Comment by UttaranB127** [comment]
It shouldn't be a big change. In fact, there are some lines in the `main.py` file inside `taew_net` to choose 16 joint poses:
```
if dataset == 'ewalk':
    num_joints = 16
    joint_parents = np.array([-1, 0, 1, 2, 2, 4, 5, 2, 7, 8, 0, 10, 11, 0, 13, 14])
```

You can check if your joint structure matches this, or change the joint parents to match your poses. The format is simple: each index `i` in `joint_parents` denotes the parent of joint `i`. The first index indicates the root, which has no parent. Therefore, the value there is -1.

We will upload the trained models soon. But you can always train from scratch if your need is more urgent.

**Comment by UttaranB127** [comment]
Closing this issue due to the long period of inactivity. Please feel free to reopen the thread if your issue is not resolved.

**Comment by Dabiaoge6** [comment]
Dear Uttaran：
Thank you for your patient reply. i want to How do you extract the rotation data. Can you provide your method to extract it?

Best wishes

**Comment by Dabiaoge6** [comment]
Dear Uttaran：
Thank you for your patient reply. I want to know how do you extract the rotation data. Can you provide your method to extract it?

Best wishes

**Comment by UttaranB127** [comment]
Unfortunately, the e-walk dataset does not come with joint rotations. Retrieving joint rotations from 3D positions is non-trivial and requires solving the inverse kinematics problem. We also provide the emotion-gait dataset, which is originally the Edinburgh Locomotion Mocap Database (https://bitbucket.org/jonathan-schwarz/edinburgh_locomotion_mocap_dataset/src/master/), relabeled with emotions for every gait. Our processed emotion-gait dataset is available here: https://drive.google.com/file/d/1-D_tT09a7CfO3JSSHWX7-Ao3SjCxTsD2/view?usp=sharing
